/* generated by dash.lucafchala.com (genUrlJs) — edit it there; the next PURL save overwrites this file.
   Loaded synchronously in <head>: sets theme/lang before first paint, wires the page on DOMContentLoaded. */
(function(){
'use strict';
var d=document.documentElement;
function ck(n){var m=document.cookie.match(new RegExp('(?:^|; )'+n+'=([^;]*)'));return m?decodeURIComponent(m[1]):null}
function ls(k){try{return localStorage.getItem(k)}catch(e){return null}}
function setPref(k,v){try{localStorage.setItem(k,v)}catch(e){}var dom=/(^|\.)lucafchala\.com$/.test(location.hostname)?'; Domain=.lucafchala.com':'';document.cookie='lf_'+k+'='+encodeURIComponent(v)+dom+'; Path=/; Max-Age=31536000; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'')}
var theme=ck('lf_theme')||ls('theme');if(theme!=='light'&&theme!=='dark')theme=window.matchMedia&&matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';
d.dataset.theme=theme;
var lang=ck('lf_lang')||ls('lang');if(lang!=='pt'&&lang!=='en')lang=/^pt/i.test(navigator.language||'')?'pt':'en';
d.dataset.lang=lang;
function applyI18n(T){d.lang=lang==='pt'?'pt-BR':'en';var t=T[lang];
document.querySelectorAll('[data-i18n]').forEach(function(e){var v=t[e.getAttribute('data-i18n')];if(v!=null)e.textContent=v});
document.querySelectorAll('[data-i18n-html]').forEach(function(e){var v=t[e.getAttribute('data-i18n-html')];if(v!=null)e.innerHTML=v});
document.querySelectorAll('[data-i18n-attr]').forEach(function(e){e.getAttribute('data-i18n-attr').split(';').forEach(function(p){var kv=p.split(':');if(t[kv[1]]!=null)e.setAttribute(kv[0],t[kv[1]])})});
document.querySelectorAll('[data-lang-btn]').forEach(function(b){b.setAttribute('aria-pressed',String(b.getAttribute('data-lang-btn')===lang))});
var m=document.querySelector('meta[name="theme-color"]');if(m)m.content=theme==='light'?'#f4efe6':'#0d0c0a'}
function wirePrefs(T,after){applyI18n(T);
document.querySelectorAll('[data-lang-btn]').forEach(function(b){b.addEventListener('click',function(){lang=b.getAttribute('data-lang-btn');d.dataset.lang=lang;setPref('lang',lang);applyI18n(T);if(after)after()})});
var tb=document.getElementById('btn-theme');if(tb)tb.addEventListener('click',function(){theme=d.dataset.theme==='dark'?'light':'dark';d.dataset.theme=theme;setPref('theme',theme);applyI18n(T)})}
var T={"pt":{"skip":"Pular para o conteúdo","prefs":"Preferências","theme":"Alternar tema","tagline":"links curtos e permanentes","pages":"PÁGINAS","links":"LINKS","filter_label":"Filtrar links","filter_ph":"filtrar…","none":"Nenhum link encontrado.","copy":"copiar","copied":"copiado!","copy_failed":"erro ao copiar","open":"abrir","g_contact":"contato","g_events":"eventos","g_video":"vídeo","g_tools":"ferramentas","hub_home":"página principal","hub_fotos":"fotografia","hub_radio":"radioamadorismo","hub_paste":"textos e snippets","hub_keys":"chaves SSH / PGP","hub_proof":"prova de identidade","hub_status":"status dos serviços","hub_dash":"painel de controle","foot":"Cada link funciona em lucafchala.com/<slug> e url.lucafchala.com/<slug>.","count_all":"links","count_of":"de"},"en":{"skip":"Skip to content","prefs":"Preferences","theme":"Toggle theme","tagline":"short, permanent links","pages":"PAGES","links":"LINKS","filter_label":"Filter links","filter_ph":"filter…","none":"No links found.","copy":"copy","copied":"copied!","copy_failed":"copy failed","open":"open","g_contact":"contact","g_events":"events","g_video":"video","g_tools":"tools","hub_home":"homepage","hub_fotos":"photography","hub_radio":"amateur radio","hub_paste":"texts and snippets","hub_keys":"SSH / PGP keys","hub_proof":"identity proof","hub_status":"service status","hub_dash":"control panel","foot":"Every link works at lucafchala.com/<slug> and url.lucafchala.com/<slug>.","count_all":"links","count_of":"of"}};
function t(k){return T[lang][k]}
function copyText(text){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(text);return new Promise(function(res,rej){var ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy')?res():rej()}catch(e){rej(e)}document.body.removeChild(ta)})}
document.addEventListener('DOMContentLoaded',function(){
  var q=document.getElementById('q'),count=document.getElementById('count'),empty=document.getElementById('empty');
  var groups=[].slice.call(document.querySelectorAll('details.group'));
  var items=[].slice.call(document.querySelectorAll('.item'));
  groups.forEach(function(g){g.dataset.open=g.open?'1':''});
  function filter(){
    var v=q.value.trim().toLowerCase(),shown=0;
    items.forEach(function(li){var ok=!v||li.getAttribute('data-q').indexOf(v)!==-1;li.hidden=!ok;if(ok)shown++});
    groups.forEach(function(g){var n=g.querySelectorAll('.item:not([hidden])').length;if(v){g.hidden=!n;g.open=n>0}else{g.hidden=false;g.open=!!g.dataset.open}});
    empty.hidden=shown>0;
    count.textContent=v?shown+' '+t('count_of')+' '+items.length:items.length+' '+t('count_all');
  }
  groups.forEach(function(g){g.addEventListener('toggle',function(){if(!q.value.trim())g.dataset.open=g.open?'1':''})});
  wirePrefs(T,filter);
  q.addEventListener('input',filter);
  filter();
  document.addEventListener('click',function(e){
    var b=e.target.closest&&e.target.closest('[data-copy]');if(!b)return;
    copyText(b.getAttribute('data-copy')).then(function(){b.textContent=t('copied');b.classList.add('ok')},function(){b.textContent=t('copy_failed')}).then(function(){setTimeout(function(){b.textContent=t('copy');b.classList.remove('ok')},2000)});
  });
  function openHash(){var id=decodeURIComponent(location.hash.slice(1));var g=id&&document.getElementById(id);if(g&&g.tagName==='DETAILS'){g.open=true;g.dataset.open='1';g.scrollIntoView()}}
  window.addEventListener('hashchange',openHash);openHash();
  document.addEventListener('keydown',function(e){if(e.key==='/'&&!/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)){e.preventDefault();q.focus()}});
});
})();
